[build]
  command = "node netlify-build-scripts/process-cms-content.js && CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
