export const homeObjOne0 = {
  id: "about",
  lightBg: true,
  ligtText: true,
  lightTextDesc: false,
  description: "As designers, We strive to offer what the client wants to gain, a functional and professional design solution. We often like to communicate with the client as the project advances so we can come out with the best possible design solution. Our portfolio is really quite diverse in range containing everything from UI/UX, Website Development to logo and editorial design to artwork we have simply created for fun. We would prefer to let our work speak for itself so feel free to have a flick through.",
  buttonlabel: "How?",
  imgStart: true,
  img: require("../../images/work.png"),
  alt: "Work Portfolio",
  dark: true,
  primary: true,
  darkText: true,
};

export const homeObjOne = {
  id: "service",
  lightBg: true,
  ligtText: true,
  lightTextDesc: false,
  headline: "Design Process",
  description: "Our comprehensive design process ensures quality and efficiency in every project.",
  buttonlabel: "Get Started",
  imgStart: false,
  img: require("../../images/designprocess.svg").default,
  alt: "Design Process",
  dark: true,
  primary: true,
  darkText: true,
};

export const homeObjOne2 = {
  id: "portfolio",
  lightBg: true,
  ligtText: true,
  lightTextDesc: false,
  topLine: "Saba Digital",
  headline: "Contact Form Design",
  description: "Modern and user-friendly contact form design for better user experience.",
  buttonlabel: "Get Started",
  imgStart: true,
  img: require("../../images/contactform.svg").default,
  alt: "Contact Form Design",
  dark: true,
  primary: true,
  darkText: true,
};

export const homeObjOne3 = {
  id: "signin",
  lightBg: false,
  ligtText: true,
  lightTextDesc: false,
  topLine: "Talk to us through",
  description: "Email: info@saba.co.ke",
  buttonlabel: "Get Started",
  imgStart: false,
  img: require("../../images/me.png"),
  alt: "Contact Information",
  dark: true,
  primary: true,
  darkText: false,
};
